apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ template "todo.fullname" . }}-todo
  name: elastic-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
